/*
 * Copyright 2026 CodeMatters, Lda.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 */

syntax = "proto3";

package spine.site.home;

import "spine/options.proto";

option (type_url_prefix) = "type.spine.io";
option java_package = "io.spine.site.home.command";
option java_outer_classname = "CommandsProto";
option java_multiple_files = true;

import "spine/site/home/identifiers.proto";

// Create a new task.
message CreateTask {
    TaskId id = 1; // assumed `required`
    string name = 2 [(required) = true];
    string description = 3;
}

// Assign a task on a user.
message AssignTask {
    TaskId task = 1;
    spine.core.UserId assignee = 2 [(required) = true];
}

// Mark a task as completed.
message CompleteTask {
    TaskId task = 1;
}
