title: Spine Event Engine documentation
description: CQRS/ES framework for modern could applications
baseurl: ""
github_username:  SpineEventEngine

# Conversion
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock

embed_code:
  code_root: ./_code
  documentation_root: ./docs
  code_includes: ["**/*.proto", "**/*.java", "**/*.kt", "**/*.dart", "**/*.js", "**/*.html", "**/*.gradle", "**/*.gradle.kts"]
